#!/usr/bin/env python3
"""Generate src/gui/theme/TailwindPalette.h from the Tailwind docs' hex map.

The docs (tailwindcss.com/docs/colors) show the canonical sRGB hex for every
palette color — the value shift+click copies. That map lives hardcoded in the
docs site source (tailwindcss.com/src/components/color.tsx, `const hexColors`)
and is the source of truth here: Tailwind's theme.css oklch literals do NOT
round-trip to those hexes (they are retuned to render more vividly), so
converting them would produce colors that differ from the docs.

Rows are emitted in the app's authored order (accent rows first, neutral
rows last), which the token->row mapping in Colors.h references by index.

Usage:
    python3 scripts/generate_tailwind_palette.py [color.tsx | URL]
The default source is the docs color.tsx on GitHub.
"""

import re
import sys
import urllib.request

DEFAULT_SOURCE = (
    "https://raw.githubusercontent.com/tailwindlabs/tailwindcss.com/"
    "main/src/components/color.tsx"
)
OUTPUT = "src/gui/theme/TailwindPalette.h"
# Palette row order (accent rows first, neutral rows last); Colors.h maps
# its hues by these indices.
ROWS = [
    "red", "orange", "amber", "yellow", "lime", "green", "emerald", "teal",
    "cyan", "sky", "blue", "indigo", "violet", "purple", "fuchsia", "pink",
    "rose", "slate", "gray", "zinc", "neutral", "stone", "mauve", "olive",
    "mist", "taupe",
]
STEPS = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"]


def parse_hex_colors(text):
    """Extract the `const hexColors = { ... }` object from color.tsx.

    Returns {row: {step: "#rrggbb"}} in file order.
    """
    m = re.search(r"const hexColors = \{(.*?)\} as any;", text, re.S)
    if not m:
        sys.exit("error: could not find the hexColors object in the source")
    body = m.group(1)
    rows = {}
    order = []
    row_re = re.compile(r"^\s{2}(\w+): \{$", re.M)
    step_re = re.compile(r'^\s{4}(\d+): "([^"]+)"', re.M)
    for row_m in row_re.finditer(body):
        name = row_m.group(1)
        order.append(name)
        seg = body[row_m.end():]
        end = seg.find("\n  },")
        seg = seg[:end] if end != -1 else seg
        rows[name] = dict(step_re.findall(seg))
    return order, rows


def emit_header(rows, source_name):
    lines = []
    ap = lines.append
    ap("// Generated by scripts/generate_tailwind_palette.py — do not edit by hand.")
    ap("// Source: %s" % source_name)
    ap("//")
    ap("// The full Tailwind CSS v4 default palette, embedded as the canonical")
    ap("// sRGB hex the docs (tailwindcss.com/docs/colors) display and copy —")
    ap("// Tailwind's theme.css Oklch literals are retuned to render more")
    ap("// vividly and do not round-trip to these hexes, so the docs hex map is")
    ap("// the source of truth. This header is pure data: rows are base colors")
    ap("// in the order below (accent rows first, neutral rows last), columns")
    ap("// are lightness steps (index 0 = 50 .. index 10 = 950). All app logic")
    ap("// (token roles, column maps, hue->row mapping) lives in Colors.h.")
    ap("#ifndef GUI_THEME_TAILWINDPALETTE_H")
    ap("#define GUI_THEME_TAILWINDPALETTE_H")
    ap("")
    ap("namespace theme {")
    ap("")
    ap("inline constexpr int kTailwindRowCount = %d;" % len(ROWS))
    ap("inline constexpr int kTailwindStepCount = %d;" % len(STEPS))
    ap("")
    ap("// [row][step] -> hex \"#rrggbb\". Rows in the order below:")
    ap("// %s" % ", ".join(ROWS))
    ap("static const char* kTailwindRows[kTailwindRowCount][kTailwindStepCount] = {")
    for row in ROWS:
        if row not in rows:
            sys.exit("error: row %r missing from the source map" % row)
        missing = [s for s in STEPS if s not in rows[row]]
        if missing:
            sys.exit("error: %s missing steps %s" % (row, ", ".join(missing)))
        hexes = ['"%s"' % rows[row][s] for s in STEPS]
        ap("    { %s }, // %s" % (", ".join(hexes), row))
    ap("};")
    ap("")
    ap("} // namespace theme")
    ap("")
    ap("#endif // GUI_THEME_TAILWINDPALETTE_H")
    ap("")
    return "\n".join(lines)


def main():
    source_arg = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE
    if source_arg.startswith("http://") or source_arg.startswith("https://"):
        with urllib.request.urlopen(source_arg) as f:
            text = f.read().decode("utf-8")
        source_name = source_arg
    else:
        with open(source_arg, "r", encoding="utf-8") as f:
            text = f.read()
        source_name = source_arg

    order, rows = parse_hex_colors(text)
    missing = [r for r in ROWS if r not in rows]
    if missing:
        sys.exit("error: source map missing rows: %s" % ", ".join(missing))

    header = emit_header(rows, source_name)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(header)
    print("wrote %s: %d rows x %d steps (%d cells) from %s"
          % (OUTPUT, len(ROWS), len(STEPS), len(ROWS) * len(STEPS), source_name))


if __name__ == "__main__":
    main()
