#ifndef GUI_THEME_ICONS_H
#define GUI_THEME_ICONS_H

#include <QColor>
#include <QString>
#include "theme/Colors.h"

namespace theme {

// Each canonical glyph is tinted with one token, chosen by its role.
enum class IconRole { Text, Muted, Hairline, Accent, Outline, Disabled };

// Token color for a role under a palette.
QColor roleColor(IconRole aRole, const Colors& aColors);

// Icon stem (e.g. "caret-down") -> role. Unknown stems default to Text.
IconRole iconRole(const QString& aStem);

// The active scratch icon dir (regenerated by tintIcons on appearance change).
QString iconDir();
void setIconDir(const QString& aDir);

// Tint the canonical currentColor set in aSrcDir into aDstDir for aColors.
void tintIcons(const QString& aSrcDir, const QString& aDstDir, const Colors& aColors);

} // namespace theme

#endif // GUI_THEME_ICONS_H
